apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  type: LoadBalancer
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: eureka-server
