apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: users-ws
  name: users-ws
spec:
  type: LoadBalancer
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    io.kompose.service: users-ws
