apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  type: LoadBalancer
  ports:
  - name: "9411"
    port: 9411
    targetPort: 9411
  selector:
    io.kompose.service: zipkin
